spring:
  datasource:
    url: jdbc:mysql://dev-host:3306/no_cicd_deploy_dev?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dev_user
    password: dev_password

  jpa:
    hibernate:
      ddl-auto: validate

app:
  jwt:
    secret: "DEV_TEMP_JWT_SECRET"
